BikesApp.WebInterface/Controllers/BikesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SztuderWiniecki.BikesApp.BLC;
using SztuderWiniecki.BikesApp.Core;
using SztuderWiniecki.BikesApp.Interfaces;
using SztuderWiniecki.BikesApp.WebInterface.ProxyModels;

namespace SztuderWiniecki.BikesApp.WebInterface.Controllers
{
    public class BikesController : Controller
    {
        private readonly BLC.BLC _blc;

        public BikesController(BLC.BLC blc)
        {
            _blc = blc;
        }

        // GET: BikesController
        public ActionResult Index(string searchString, string typeFilter, int? yearFrom, int? yearTo)
        {
            var bikes = _blc.GetBikes();
            if (!String.IsNullOrEmpty(searchString))
            {
                bikes = bikes.Where(s => s.Name!.Contains(searchString, System.StringComparison.CurrentCultureIgnoreCase) || s.Producer.Name!.Contains(searchString, System.StringComparison.CurrentCultureIgnoreCase));
            }

            if(!String.IsNullOrEmpty(typeFilter))
            {
                bikes = bikes.Where(s => s.Type.ToString() == typeFilter);
            }

            if (yearFrom != null)
            {
                bikes = bikes.Where(b => b.ReleaseYear >= yearFrom);
            }

			if (yearTo != null)
			{
				bikes = bikes.Where(b => b.ReleaseYear <= yearTo);
			}

			ViewBag.Types = Enum.GetNames(typeof(BikeType));

			ViewBag.SearchString = searchString;
			ViewBag.yearFrom = yearFrom;
			ViewBag.yearTo = yearTo;
            ViewBag.TypeFilter = typeFilter;


            return View(bikes);
        }

        // GET: BikesController/Details/5
        public ActionResult Details(int id)
        {
            IBike? bike = _blc.GetBike(id);
            if (bike == null)
            {
                return NotFound();
            }
            
            return View(bike);
        }

        // GET: BikesController/Create
        public ActionResult Create()
        {
            ViewBag.Producers = _blc.GetProducers();
            ViewBag.Types = Enum.GetNames(typeof(BikeType));
            return View(_blc.CreateBike());
        }

        // POST: BikesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,Name,ReleaseYear,Type")] ProxyBike bike, [Bind("Producer")] int Producer)
        {
            // cannot bind to interface, so we create proxy object and rewrite its values to DAO object
            IBike? daoBike = _blc.CreateBike();

            daoBike.CopyFrom(bike);

            IProducer? producer = _blc.GetProducer(Producer);
            if (producer == null)
            {
                return NotFound();
            }

            daoBike.Producer = producer;


            ModelState.Remove("Producer");
            if (ModelState.IsValid)
            {
                try
                {
                    _blc.AddBike(daoBike);
                    _blc.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bike);
        }


        // GET: BikesController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IBike? bike = _blc.GetBike((int)id);
            if(bike == null)
            {
                return NotFound();
            }

            ViewBag.Producers = _blc.GetProducers();
            ViewBag.Types = Enum.GetNames(typeof(BikeType));

            return View(bike);
        }

        // POST: BikesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Id,Name,ReleaseYear,Type")] ProxyBike bike, [Bind("Producer")] int Producer)
        {
            if (id != bike.Id)
            {
                return NotFound();
            }

            // cannot bind to interface, so we create proxy object and rewrite its values to DAO object
            IBike? daoBike = _blc.GetBike(bike.Id);
            if(daoBike == null)
            {
                return NotFound();
            }

            daoBike.CopyFrom(bike);

            IProducer? producer = _blc.GetProducer(Producer);
            if(producer == null)
            {
                return NotFound();
            }

            daoBike.Producer = producer;
            

            ModelState.Remove("Producer");
            if (ModelState.IsValid)
            {
                try
                {
                    _blc.UpdateBike(daoBike);
                    _blc.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bike);
        }

        // GET: BikesController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IBike? bike = _blc.GetBike((int)id);
            if (bike == null)
            {
                return NotFound();
            }

            return View(bike);
        }

        // POST: BikesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [Bind("Id,Name,ReleaseYear,Type,Producer")] ProxyBike bike)
        {
            _blc.RemoveBike(id);
            _blc.SaveChanges();
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return NotFound();
            }
        }
    }
}

BikesApp.WebInterface/Views/Bikes/Create.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IBike

@{
    ViewData["Title"] = "Create";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>IBike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseYear" class="control-label"></label>
                <input asp-for="ReleaseYear" class="form-control" />
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select class="form-control selectpicker" asp-for="Type" name="Type" data-live-search="true">
                    @foreach (var type in ViewBag.Types)
                    {
                        <option value="@type">@type</option>
                    }
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <select class="form-control selectpicker" asp-for="Producer" name="Producer" data-live-search="true">
                    @foreach (var producer in ViewBag.Producers)
                    {
                        <option value="@producer.Id">@producer.Name</option>
                    }
                </select>
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <button type="submit" class="btn btn-success">
                    <i class="me-2 bi bi-plus-square"></i>
                    <span>
                        Create
                    </span>
                </button>

                <a href="@Url.Action("Index", "Bikes")" class="btn btn-danger">
                    <i class="me-2 bi bi-box-arrow-in-right"></i>
                    <span>
                        Cancel
                    </span>
                </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BikesApp.WebInterface/Views/Bikes/Delete.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IBike

@{
    ViewData["Title"] = "Delete";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IBike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <button type="submit" value="Delete" class="btn btn-danger me-2">
            <i class="me-2 bi bi-trash"></i>
            <span>
                Delete
            </span>
        </button>
        <a href="@Url.Action("Index", "Bikes")" class="btn btn-info">
            <i class="me-2 bi bi-box-arrow-in-right"></i>
            <span>
                Back to List
            </span>
        </a>
    </form>
</div>

BikesApp.WebInterface/Views/Bikes/Details.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IBike

@{
    ViewData["Title"] = "Details";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>View</h1>

<div>
    <h4>IBike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Producer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Producer.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a href="@Url.Action("Edit", "Bikes", new { Model.Id })" class="btn btn-primary">
        <i class="me-2 bi bi-pencil-square"></i>
        <span>
            Edit
        </span>
    </a>
    <a href="@Url.Action("Index", "Bikes")" class="btn btn-info">
        <i class="me-2 bi bi-box-arrow-in-right"></i>
        <span>
            Back to List
        </span>
    </a>
</div>

BikesApp.WebInterface/Views/Bikes/Edit.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IBike

@{
    ViewData["Title"] = "Edit";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>IBike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseYear" class="control-label"></label>
                <input asp-for="ReleaseYear" class="form-control" />
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select class="form-control selectpicker" asp-for="Type" name="Type" data-live-search="true">
                    @foreach (var type in ViewBag.Types)
                    {
                        <option value="@type">@type</option>
                    }
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <select class="form-control selectpicker" asp-for="Producer" name="Producer" data-live-search="true">
                    @foreach (var producer in ViewBag.Producers)
                    {
                        <option value="@producer.Id" selected="@(producer.Id == Model.Producer.Id)">@producer.Name</option>
                    }
                </select>
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="mt-2 form-group">
                <button type="submit" value="Save" class="btn btn-success">
                    <i class="me-2 bi bi-floppy"></i>
                    Save
                </button>
                <a href="@Url.Action("Index", "Bikes")" class="btn btn-danger">
                    <i class="me-2 bi bi-box-arrow-in-right"></i>
                    <span>
                        Cancel
                    </span>
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BikesApp.WebInterface/Views/Bikes/Index.cshtml
@model IEnumerable<SztuderWiniecki.BikesApp.Interfaces.IBike>

@{
    ViewData["Title"] = "View";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Bikes list</h1>

<div class="mb-3">
    <div>
        <form asp-controller="Bikes" asp-action="Index" method="get" class="col-12 row">
            <div class="col-12 row">
                <div class="col-2">
                    <span>Type</span>
                </div>
                <div class="col-4">
                    <select class="form-select" name="TypeFilter">
                        <option value="">All</option>
                        @foreach (var type in ViewBag.Types)
                        {
                            <option value="@type" selected="@(ViewBag.TypeFilter == type)">@type</option>
                        }
                    </select>
                </div>

                <div class="col-2">
                    <span>Release year</span>
                </div>
                <div class="col-2">
                    <input type="number" name="YearFrom" value=@ViewBag.YearFrom class="form-control" />
                </div>
                <div class="col-2">
                    <input type="number" name="YearTo" value=@ViewBag.YearTo class="form-control" />
                </div>

            </div>
            <div class="col-9">
                <input type="text" name="SearchString" placeholder="Search..." value=@ViewBag.SearchString class="form-control" />
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-primary w-100">
                    <i class="bi bi-search"></i> 
                    Search
                </button>
            </div>
        </form>
    </div>
</div>

<p>
    <a href="@Url.Action("Create", "Bikes")" class="btn btn-primary">
        <i class="me-2 bi bi-plus-square"></i>
        <span>
            Add Bike
        </span>
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @item.Producer.Name
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                    <a href="@Url.Action("Edit", "Bikes", new { item.Id })" class="btn btn-primary">
                        <i class="me-2 bi bi-pencil-square"></i>
                        <span>
                            Edit
                        </span>
                    </a>
                    <a href="@Url.Action("Details", "Bikes", new { item.Id })" class="btn btn-primary">
                        <i class="me-2 bi bi-card-list"></i>
                        <span>
                            Details
                        </span>
                    </a>
                    <a href="@Url.Action("Delete", "Bikes", new { item.Id })" class="btn btn-danger">
                        <i class="me-2 bi bi-trash3"></i>
                        <span>
                            Delete
                        </span>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>