BikesApp.WebInterface/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SztuderWiniecki.BikesApp.BLC;
using SztuderWiniecki.BikesApp.Interfaces;
using SztuderWiniecki.BikesApp.WebInterface.ProxyModels;

namespace SztuderWiniecki.BikesApp.WebInterface.Controllers
{
    public class ProducersController : Controller
    {
        private readonly BLC.BLC _blc;

        public ProducersController(BLC.BLC blc)
        {
            _blc = blc;
        }

        // GET: ProducersController
        public ActionResult Index(string searchString)
        {
            var producers = _blc.GetProducers();

            if (!String.IsNullOrEmpty(searchString))
            {
                producers = producers.Where(s => s.Name!.Contains(searchString, System.StringComparison.CurrentCultureIgnoreCase) || s.Address!.Contains(searchString, System.StringComparison.CurrentCultureIgnoreCase));
            }

            ViewBag.SearchString = searchString;

            return View(producers);
        }

        // GET: ProducersController/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IProducer? producer = _blc.GetProducer((int)id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // GET: ProducersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProducersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id, Name, Address")] ProxyProducer producer)
        {
            if (ModelState.IsValid)
            {
                IProducer daoProducer = _blc.CreateProducer().CopyFrom(producer);

                _blc.AddProducer(daoProducer);
                _blc.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Create));
        }

        // GET: ProducersController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IProducer? producer = _blc.GetProducer((int)id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // POST: ProducersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Id, Name, Address")] ProxyProducer producer)
        {
            if (id != producer.Id)
            {
                return NotFound();
            }

            // cannot bind to interface, so create proxy object and rewrite its values to DAO object
            IProducer? daoProducer = _blc.GetProducer(producer.Id);
            if (daoProducer == null)
            {
                return NotFound();
            }

            daoProducer.CopyFrom(producer);

            if (ModelState.IsValid)
            {
                try
                {
                    _blc.UpdateProducer(daoProducer);
                    _blc.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    /*if (!BikeExists(bike.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }*/
                }
                return RedirectToAction(nameof(Index));
            }
            return View(daoProducer);
        }

        // GET: ProducersController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IProducer? producer = _blc.GetProducer((int)id);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // POST: ProducersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [Bind("Id, Name, Address")] ProxyProducer producer)
        {
            _blc.RemoveProducer(id);
            _blc.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

BikesApp.WebInterface/Views/Producers/Create.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IProducer

@{
    ViewData["Title"] = "Create";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>IProducer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <button type="submit" class="btn btn-success">
                    <i class="me-2 bi bi-plus-square"></i>
                    <span>
                        Create
                    </span>
                </button>

                <a href="@Url.Action("Index", "Producers")" class="btn btn-danger">
                    <i class="me-2 bi bi-box-arrow-in-right"></i>
                    <span>
                        Cancel
                    </span>
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BikesApp.WebInterface/Views/Producers/Delete.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IProducer

@{
    ViewData["Title"] = "Delete";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IProducer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <button type="submit" value="Delete" class="btn btn-danger me-2">
            <i class="me-2 bi bi-trash"></i>
            <span>
                Delete
            </span>
        </button>
        <a href="@Url.Action("Index", "Producers")" class="btn btn-info">
            <i class="me-2 bi bi-box-arrow-in-right"></i>
            <span>
                Back to List
            </span>
        </a>
    </form>
</div>

BikesApp.WebInterface/Views/Producers/Details.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IProducer

@{
    ViewData["Title"] = "Details";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>IProducer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a href="@Url.Action("Edit", "Producers", new { Model.Id })" class="btn btn-primary">
        <i class="me-2 bi bi-pencil-square"></i>
        <span>
            Edit
        </span>
    </a>
    <a href="@Url.Action("Index", "Producers")" class="btn btn-info">
        <i class="me-2 bi bi-box-arrow-in-right"></i>
        <span>
            Back to List
        </span>
    </a>
</div>

BikesApp.WebInterface/Views/Producers/Edit.cshtml
@model SztuderWiniecki.BikesApp.Interfaces.IProducer

@{
    ViewData["Title"] = "Edit";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>IProducer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <button type="submit" value="Save" class="btn btn-success">
                    <i class="me-2 bi bi-floppy"></i>
                    Save
                </button>
                <a href="@Url.Action("Index", "Producers")" class="btn btn-info">
                    <i class="me-2 bi bi-box-arrow-in-right"></i>
                    <span>
                        Back to List
                    </span>
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BikesApp.WebInterface/Views/Producers/Index.cshtml
@model IEnumerable<SztuderWiniecki.BikesApp.Interfaces.IProducer>

@{
    ViewData["Title"] = "Index";
}

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<h1>Producers list</h1>

<div class="mb-3">
    <div>
        <form asp-controller="Producers" asp-action="Index" method="get" class="col-12 col-xl-6 row">
            <div class="col-9">
                <input type="text" name="SearchString" placeholder="Search..." value=@ViewBag.SearchString class="form-control" />
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-primary"> <i class="bi bi-search"></i> </button>
            </div>
        </form>
    </div>
</div>

<p>
    <a href="@Url.Action("Create", "Producers")" class="btn btn-primary">
        <i class="me-2 bi bi-plus-square"></i>
        <span>
            Add producer
        </span>
    </a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                    <a href="@Url.Action("Edit", "Producers", new { item.Id })" class="btn btn-primary">
                        <i class="me-2 bi bi-pencil-square"></i>
                        <span>
                            Edit
                        </span>
                    </a>
                    <a href="@Url.Action("Details", "Producers", new { item.Id })" class="btn btn-primary">
                        <i class="me-2 bi bi-card-list"></i>
                        <span>
                            Details
                        </span>
                    </a>
                    <a href="@Url.Action("Delete", "Producers", new { item.Id })" class="btn btn-danger">
                        <i class="me-2 bi bi-trash3"></i>
                        <span>
                            Delete
                        </span>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>